package com.gensynth.plugin.api;

import java.util.List;

/**
 * Entry point of a GenSynth connector plugin: the only interface a plugin implements.
 *
 * A connector sends the messages generated by a flow to a technology (a broker, a socket,
 * a file...). The plugin declares:
 * <ul>
 *   <li>{@link #info()}: who it is (id, name, version, description);</li>
 *   <li>{@link #fields()}: the configuration fields it needs, in display order. GenSynth renders
 *       them in the flow configuration, validates the values and applies defaults;</li>
 *   <li>{@link #connect(ConnectorConfig, ConnectorContext)}: how to open a connection that sends
 *       messages.</li>
 * </ul>
 *
 * Register the implementation with the Java ServiceLoader, in
 * {@code META-INF/services/com.gensynth.plugin.api.ConnectorPlugin}. It needs a public
 * no-argument constructor and should be stateless: GenSynth creates one instance and calls
 * {@link #connect} once per flow.
 */
public interface ConnectorPlugin {

    /**
     * @return identity of the connector, shown in the connector selector
     */
    ConnectorInfo info();

    /**
     * @return the configuration fields, in the order they are shown to the user
     */
    List<ConnectorField> fields();

    /**
     * Opens a connection for one flow. Called when the flow's group starts.
     *
     * @param config  values of {@link #fields()}, already validated, typed and with defaults applied
     * @param context runtime information about the flow
     * @return an open session used to send the flow's messages
     * @throws Exception if the connection cannot be opened (the flow is marked as failed)
     */
    ConnectorSession connect(ConnectorConfig config, ConnectorContext context) throws Exception;
}
